### ISSUE TITLE
Quilt Suppoert?

### ISSUE THREAD

**Issue by ImBehinYa** [StickyPiston-development/CreateCobblestone#1]
Hi,

amazing mod idea.

Does this mod really depend on fabric 0.92.0

because quiltet fabric for 1.20.1 only is 0.91.0

Thanks

**Comment by MrStickyPiston** [comment]
Im working on it

**Comment by MrStickyPiston** [comment]
@ImBehinYa i got it working, can you test it before i release it

Download the fabric-artifacts from https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/9284420050
and extract createcobblestone-1.1.0+fabric-1.20.1-19.jar to your quilt mods folder.

**Comment by ImBehinYa** [comment]
No collision and no axis wit the current build

![image](https://github.com/StickyPiston-development/CreateCobblestone/assets/63367722/01ed6911-439c-42e2-a805-cfc6bef3569d)



i change the fabric json from your first released mod and i just changed 0.92.0 to 0.91.0 in the dependecys and it worked.
But it is hacky and my cause issues

**Comment by MrStickyPiston** [comment]
I have seen that glitch before, but on fabric. It happened once in 100 times booring fabric. Can you send logs and how common is it for you?

**Comment by ImBehinYa** [comment]
Okay it works, 
if i disable Pehkui
so https://modrinth.com/mod/pehkui incompatible

**Comment by MrStickyPiston** [comment]
Quilt support is now on modrinth, https://modrinth.com/mod/create-cobblestone/version/1.1.0+fabric-1.20.1-19. Can i mark this issue as resolved?
