### ISSUE TITLE
GeneratorRatio Value in Config File does nothing [bug]

### ISSUE THREAD

**Issue by SkyPhoenixZ1000** [StickyPiston-development/CreateCobblestone#15]
Version: Create Cobblestone 1.3.2+fabric-1.20.1-38
Fabric loader: 0.15.11-1.20.1

When you change GeneratorRatio Value it does literally nothing, no increasement nor decreasement of yield in generating stone, it always produce the exact same amount of item per cycle.

**Comment by MrStickyPiston** [comment]
what did you change it to?

changing it to 100 does reduce the amount of cobblestone significantly for what i tested, _after the backup has been emptied_

**Comment by SkyPhoenixZ1000** [comment]
My bad for misunderstanding, i previously set values to 0.1, 0.2, 0.5, 16, 32 but didnt see any differences, never thought i was supposed to set a value to at least 100 and beyond to make significant change of yield. Luckily your hint helped, after some quick tests, i set final value to 1180 so the efficiency wont go too much beyond 4 stacks per minute per mechanical stone generator.

**Comment by SkyPhoenixZ1000** [comment]
I think this thread can be closed now!

**Comment by MrStickyPiston** [comment]
Ther actually is a formula when you hover the setting. But im happy this is solved.

**Comment by MrStickyPiston** [comment]
I found the problem: the forge config system is not loaded when the blocks are added, so the default values are added. I dont know a fix yet.
