### ISSUE TITLE
Update to create 0.5.1-f

### ISSUE THREAD

**Issue by Schoktra** [StickyPiston-development/CreateCobblestone#16]
Please change the way the mod requires create mod. Create mod had a bug in which you couldn't put "unbreakable" on the back tank, place it in a contraption to refill it, then pick it back up, it would clear the "unbreakable" tag making it start taking damage again.  When I mentioned this to the create developers, they either fixed it or had previously fixed it in an upcoming version, but your mod makes it impossible to use the updated version. Your mod uses exact versioning on its requirement of create mod, and should be using a minimum requirement instead. As in, it should be set up "requires 0.5.1-f or later" not "requires 0.5.1-f".

**Comment by MrStickyPiston** [comment]
It uses exact versioning because things might break. Will try to port soon.

**Comment by MrStickyPiston** [comment]
it uses create 0.5.1-f now
