### ISSUE TITLE
Generator spins when attached to power and doesn't give items

### ISSUE THREAD

**Issue by danielr1996** [StickyPiston-development/CreateCobblestone#17]
When trying to use any generator the generator starts to spin (there are now two generators, the placed block, and a "copy" that spins and glitches through the original block)

However a few weeks ago (i'm pretty sure I used the same version then since the last version was releases two months ago) everything worked, but I unfortunately do not have the modpack I used then anymore. So I guess the issue is with another mod, not this mod itself.

![2024-09-11_23 15 29](https://github.com/user-attachments/assets/12ef2e4d-f0b1-4588-a7f9-9edbf1e2208c)

Logs: https://mclo.gs/SMZyqOX

Other installed mods:  https://github.com/block-buddies/ingenium-create-and-beyond/blob/main/index.toml (I hope you can work with a packwiz modpack, if not please let me know how I can send you the mrpack, I think it's to large to upload on github.

Version: 1.3.2+fabric-1.20.1-38

**Comment by MrStickyPiston** [comment]
Did you started to use shaders?

**Comment by danielr1996** [comment]
No I used shaders before, but I will try it with shaders disabled.

**Comment by danielr1996** [comment]
Yes it's the shaders, and the issue with items not dropping was because I didn't attach a funnel to it, so it's pure a visual glitch

**Comment by MrStickyPiston** [comment]
Please install iris oculus flywheel compat

**Comment by danielr1996** [comment]
I think I also had this installed in my old modpack which explains why it worked there.
