### ISSUE TITLE
The generator doesnt show up in JEI/Creative tab.  Latest forge beta test

### ISSUE THREAD

**Issue by Looxond** [StickyPiston-development/CreateCobblestone#18]
It however can be seen in the crafting book and can be made in a regular crafting table

**Comment by MrStickyPiston** [comment]
Does it work if you use the creative search with "generator" as query?

**Comment by Looxond** [comment]
> Does it work if you use the creative search with "generator" as query?

nope
![2024-09-18_17 25 58](https://github.com/user-attachments/assets/0537d055-7962-4799-8d91-b63ecf5bd0ae)

**Comment by MrStickyPiston** [comment]
can you send me your logs

**Comment by Looxond** [comment]
> can you send me your logs

Here you go. https://mclo.gs/QNuMH2H

**Comment by MrStickyPiston** [comment]
what happens if you only use JEI, Architectury api, Create and Create Cobblestone? I can confirm that jei doesnt work but creative tab search seems to work.
![2024-09-21_12 33 04](https://github.com/user-attachments/assets/85cab48e-b5f0-4e17-8dd1-5f6e18eca7d9)

**Comment by MrStickyPiston** [comment]
commit 9857377 fixed it. I will be releasing this version on modrinth and curseforge soon as release.

**Comment by MrStickyPiston** [comment]
Published on modrinth:

https://modrinth.com/mod/create-cobblestone/version/1.4+fabric-1.20.1-51
https://modrinth.com/mod/create-cobblestone/version/1.4+forge-1.20.1-51

**Comment by MrStickyPiston** [comment]
**Curseforge**
Fabric: https://www.curseforge.com/minecraft/mc-mods/create-cobblestone/files/5827514
Forge: https://www.curseforge.com/minecraft/mc-mods/create-cobblestone/files/5827516
