### ISSUE TITLE
log spamming in console

### ISSUE THREAD

**Issue by realspinelle** [StickyPiston-development/CreateCobblestone#19]
hey i just made a pack in 1.20.1 including createcobblestone using 1.4-beta+forge-1.20.1-49
but i guess somewhere there is a forgotten log or something as its spamming my console
![image](https://github.com/user-attachments/assets/13651d70-017b-4282-a2d6-343a980d15b3)

**Comment by MrStickyPiston** [comment]
Sorry i forgot about it, i will fix it tomorrow.

**Comment by MrStickyPiston** [comment]
Modrinth approved.
fabric: https://modrinth.com/mod/create-cobblestone/version/1.4-beta-2+fabric-1.20.1-50 
forge: https://modrinth.com/mod/create-cobblestone/version/1.4-beta-2+forge-1.20.1-50
