### ISSUE TITLE
Change Generation Rate to something lower than 1/T, game just crashes

### ISSUE THREAD

**Issue by AstroneerAddict** [StickyPiston-development/CreateCobblestone#2]
is it possible to have the thing not produce during a tick and  during a time period? like 1/S, for more balanced configuration.
since otherwise it's always a minimum of one a tick, which is just not possible to config balance really.

-Astro

**Comment by MrStickyPiston** [comment]
will look into it. It could be hard because minecraft runs on ticks.

Edit: typo

**Comment by MrStickyPiston** [comment]
I got the problem. The datatype used for that config value is float, so 0.x is converted into 0. And then zero division crashesz the game.

**Comment by MrStickyPiston** [comment]
![2024-06-24_17 34 16](https://github.com/StickyPiston-development/CreateCobblestone/assets/97804691/3cd91b11-93a8-407e-ab2f-07a6d34a6c41)
![2024-06-24_17 36 32](https://github.com/StickyPiston-development/CreateCobblestone/assets/97804691/baba1dcb-e9cc-4bd0-9a5b-17cb5555f7dc)

i think i "fixed" it by making it not possible to occur.

**Comment by MrStickyPiston** [comment]
I did some backend changes and now it even works with really slow generators. I hope this is what you meant.
https://github.com/StickyPiston-development/CreateCobblestone/assets/97804691/59ca76f4-8cb6-447a-822a-01da90267eb0

**Comment by AstroneerAddict** [comment]
ooh that looks great, very much thanking you, tysm. :D

**Comment by MrStickyPiston** [comment]
No problem, i will release this in a few days on modrinth.

**Comment by MrStickyPiston** [comment]
Here you go! (for forge, neoforge, fabric and quilt.
https://modrinth.com/mod/create-cobblestone/version/1.3.1+forge-1.20.1-36
https://modrinth.com/mod/create-cobblestone/version/1.3.1+fabric-1.20.1-36
