### ISSUE TITLE
Block Drop

### ISSUE THREAD

**Issue by NekrosTDS** [StickyPiston-development/CreateCobblestone#20]
Warning: I don't know English perfectly, if there are any mistakes, please let me know.
___________________________________________________
I wanted to open this topic because it was not resolved
When trying to break the generator, the block did not fall Out. Also with Shift+RMB with a wrench.

**Comment by MrStickyPiston** [comment]
Could you please send the minecraft latest.log?

**Comment by NekrosTDS** [comment]
> Could you please send the minecraft latest.log?

Let me clarify, should I provide a log with the moment the block was broken?

**Comment by MrStickyPiston** [comment]
Just the whole log of the time it did not drop, including startup and shutdown

**Comment by NekrosTDS** [comment]
[latest.log](https://github.com/user-attachments/files/17254906/latest.log)
I also want to note that the block breaks like in creativity

**Comment by MrStickyPiston** [comment]
Could you try the beta? IN A TEST WORLD IT WILL DELETE ALL GENERATORS

**Comment by NekrosTDS** [comment]
I didn't quite understand you, should I reset the logs with the beta version of the mod?

**Comment by NekrosTDS** [comment]
[latest.log](https://github.com/user-attachments/files/17255239/latest.log)
I want to say that I ran a clean build with only the Create mod and Create Cobblestone
and everything worked normally, maybe it is due to a conflict of mods in the assembly?

**Comment by NekrosTDS** [comment]
Updated the build mod, everything worked.
I have no more questions
thank you for giving me your time

**Comment by MrStickyPiston** [comment]
No problem, i will close this issue then
