### ISSUE TITLE
1.4.1 Beta icompatible with create liquid fuel

### ISSUE THREAD

**Issue by SageofTurtles** [StickyPiston-development/CreateCobblestone#21]
Hello!  I am updating some mods in my pack, and have encountered an issue with the latest two versions of Create Cobblestone.  Upon launching the game, I get the typical Forge loading screen, and as soon as the loading is complete the game crashes.  It runs fine with version 1.4+forge-1.20.1-51 of the mod installed, but the crashes occur when I use either of the two 1.4.1 beta releases published yesterday.  Below are the crash reports, one from each version of the mod release.

[crash-1.4.1-beta+forge-1.20.1-56.txt](https://github.com/user-attachments/files/17528518/crash-1.4.1-beta%2Bforge-1.20.1-56.txt)
[crash-1.4.1-beta-2+forge-1.20.1-59.txt](https://github.com/user-attachments/files/17528519/crash-1.4.1-beta-2%2Bforge-1.20.1-59.txt)

Currently using:
- Forge 47.3.11
- Minecraft 1.20.1
- Create 0.5.1.j
(This version of Create is the newest release from Oct. 23, which might be part of the issue, since I updated both mods at the same time.)

**Comment by MrStickyPiston** [comment]
Could you try it on a clean installation? A lot of mods appear in the error making it hard to read.

**Comment by MrStickyPiston** [comment]
I found the problem, it is an incompatibility between create liquid fuel and create cobblestone. Im working on fixing it.

**Comment by MrStickyPiston** [comment]
I fixed it, it works now but will still throw an error in the logs to make sure i can debug it if it breaks in some other mod.

**Comment by MrStickyPiston** [comment]
It will take some time before i upload this to modrinth, but for now you can use the github actions build:
https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/11540472797/artifacts/2109088758

**Comment by SageofTurtles** [comment]
Thank you for the quick fix! I'm looking forward to adding this to my server :)

**Comment by MrStickyPiston** [comment]
No problem! Is the modpack for your server public?

**Comment by SageofTurtles** [comment]
Not currently, I'm working on overhauling the modpack for season 2 (which includes switching from Fabric to Forge), so there's quite a lot of work to do before it's ready to share. At some point I'm wanting to have it available to download on our server's website, but haven't gotten that far yet.

**Comment by MrStickyPiston** [comment]
Modrinth approved the files.

Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-3+fabric-1.20.1-65
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-3+forge-1.20.1-65
Datapack: https://modrinth.com/datapack/create-cobblestone-deepslate-generators/version/1.4.1+1.20.1
