### ISSUE TITLE
Crash when hovering over Mechanical Generator in EMI

### ISSUE THREAD

**Issue by undefined06855** [StickyPiston-development/CreateCobblestone#22]
fabric 1.20.1 on my own server, [https://mclo.gs/2KkH0PU](https://mclo.gs/2KkH0PU)

**Comment by MrStickyPiston** [comment]
Please try this version: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-4+fabric-1.20.1-72. It solves a crash like this.

**Comment by undefined06855** [comment]
Yeah this fixes the issue for me, thanks
