### ISSUE TITLE
Can't get custom generators to work

### ISSUE THREAD

**Issue by EightBitBBQ** [StickyPiston-development/CreateCobblestone#23]
I cant figure out how to add more custom generators.
In this example i tried ice for example. But i cant put ice in the generator.
No matter what i try. Even adding lines to the Mod config to "enable" it didnt work.

Am i missing out on something?
Loader: Forge
Version: 1.20.1
Mods: Create, Create Cobblestone Generator and JEI
[CreateCobblestone_generators.zip](https://github.com/user-attachments/files/17801113/CreateCobblestone_generators.zip)

**Comment by MrStickyPiston** [comment]
Please upload logs with the pack enabled

**Comment by EightBitBBQ** [comment]
I cant even start now
[crash-2024-11-18_15.32.17-client.txt](https://github.com/user-attachments/files/17801861/crash-2024-11-18_15.32.17-client.txt)
 :(

**Comment by EightBitBBQ** [comment]
[latest.log](https://github.com/user-attachments/files/17801929/latest.log)
This is on a custom pack. It works here.

At the end you can see the pack is enabled. But still not working sadly

**Comment by MrStickyPiston** [comment]
To use custom generators, you need the 1.4.1-beta-4 version on both the server and the client. Your server currently has the 1.4 version, that is why you are crashing.

**Comment by EightBitBBQ** [comment]
Uh, hold on.
I was playing Single player?
Couldnt even launch the game

**Comment by EightBitBBQ** [comment]
But my main issue is still, i cant generator custom generators?
I need help on that

**Comment by MrStickyPiston** [comment]
Install the beta then

**Comment by EightBitBBQ** [comment]
Okay. Sorry i guess?

Gl on what ever mate

**Comment by EightBitBBQ** [comment]
For everyone who will read this and actually want a usefull reaction.

Yes updating to a beta version worked..

Thanks @MrStickyPiston

**Comment by MrStickyPiston** [comment]
Sorry, i was on my phone and did not have time for a good search in the logs and thought you were on a server due to how forge logs it. 

To clarify: 1.4.1-beta+ contains the custom generators.

**Comment by EightBitBBQ** [comment]
Its fine. Im dutch myself, i know how "rude" we can sound, but not intend to be.

But yeah, after updating to 1.4.1-beta-4 version. It all worked out. Ty!!
