### ISSUE TITLE
Client got spammed with NullPointerException

### ISSUE THREAD

**Issue by NantaArthur123** [StickyPiston-development/CreateCobblestone#24]
I don't know the main cause of the error spam because I only receive the info after I join the server.
but client got this message
`[15:43:54] [Render thread/INFO]: [CHAT] java.lang.NullPointerException: Cannot invoke "net.createcobblestone.data.GeneratorType.getId()" because "net.createcobblestone.data.GeneratorType.NONE" is null`

Modloader: Fabric 0.16.9
Mc version: 1.20.1

**Comment by MrStickyPiston** [comment]
Just spam or also crashes?

**Comment by NantaArthur123** [comment]
no crashes, but after server restart no error ever occurred again (for the last 8 hours)

**Comment by MrStickyPiston** [comment]
As it did not hurt anything i think it was just a small delay in networking. Im closing this issue, but if you crash due to this, please reopen it.
