### ISSUE TITLE
Update to Create 1.51-j

### ISSUE THREAD

**Issue by danielhkuo** [StickyPiston-development/CreateCobblestone#26]
If possible, could you please update for the latest version of Create. Thank you!

`Replace mod 'Create Cobblestone' (createcobblestone) 1.4.1+fabric-1.20.1-73 with any version that is compatible with: create 0.5.1-j-build.1604+mc1.20.1`

**Comment by MrStickyPiston** [comment]
Will update soon now that both forge and fabric are updated

**Comment by MrStickyPiston** [comment]
can you try out https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/12138568941

**Comment by danielhkuo** [comment]
Thanks, seems to be working.
