### ISSUE TITLE
Generator not working - console error message

### ISSUE THREAD

**Issue by chimaeraUndying** [StickyPiston-development/CreateCobblestone#27]
1.20.1, Create 0.5.1.j, Create cobblestone 1.4.2 (though I was having this issue with prior versions of Create and CCobble as well). This issue occurs with the mod's default config:

Generators don't produce cobble. Getting this in the log whenever I place or interact with one:
`[02:19:18] [Render thread/INFO] [Create cobblestone/]: Trying to update generator type from "none" to "none"`
`[02:19:18] [Render thread/INFO] [Create cobblestone/]: Changing generator type from "none" to "none"`

I assume something's gotten confused in the backend.

**Comment by MrStickyPiston** [comment]
Please send the full log and a screenshot/video of you placing the generator

**Comment by chimaeraUndying** [comment]
Never mind, I figured it out! Turns out I'm just stupid and didn't realize you had to right-click on the generator with a cobblestone (or other) block to get it going. Sorry!
