### ISSUE TITLE
Recipe/Item visibility

### ISSUE THREAD

**Issue by lucifer650** [StickyPiston-development/CreateCobblestone#4]
JEI does not show the items at all. And the item recipes are not in the vanilla recipe book. Also not available in the creative menu. I legitimately thought I didn't have the mod installed until I tried to install it again. Funny enough the config is still there and I can get the items through console commands. But I can only get the items through manually placing the crafting items in the right slots by referencing the images on the modpage, and using console commands. Game version 1.20.1

**Comment by lucifer650** [comment]
I did a bunch of looking around across like 50 different reddit forums and quora posts and all that fun stuff. And found it was a forge problem that pretty much everyone can have, and is a hit or miss thing. But the fixes are pretty easy.
Fix 1: [https://www.reddit.com/r/CreateMod/comments/1dggv32/comment/l8sxg4p/?context=3&share_id=xb8u08kjwtPnYObbS4k_A&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1](url)
Fix 2: [https://github.com/Creators-of-Create/Create/issues/6222#issuecomment-2142451391](url)
I personally used both, and fix 1 is more flexible for new mods and acts as just a secondary failsafe. But I definitely recommend getting both as it doesn't hurt anything if you do. Only benefits. Hope this helps anyone else!

**Comment by MrStickyPiston** [comment]
Should i do anything with this?
