### ISSUE TITLE
Additional stone type production: (cobbled) deepslate

### ISSUE THREAD

**Issue by BonezTheWonderful** [StickyPiston-development/CreateCobblestone#5]
Just like the config shows for enabling lime stone and scoria add deepslate and cobbled deepslate
seeing as those cant be farmed in anyway rightnow

**Comment by MrStickyPiston** [comment]
Limestone and scoria can be generated, check the create wiki.

Deepslate can not, so the generator will be disabled at default.

**Comment by MrStickyPiston** [comment]
Feature has been implemented, please try out the actions build: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/9909296809. If it works i will release it on modirnth and later curseforge.

**Comment by BonezTheWonderful** [comment]
> Feature has been implemented, please try out the actions build: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/9909296809. If it works i will release it on modirnth and later curseforge.

Cool but i'm not too familar with stuff like this so it might take some time

**Comment by MrStickyPiston** [comment]
For myself i didnt encounter bugs so i will upload it.

**Comment by MrStickyPiston** [comment]
Uploaded it as beta
