### ISSUE TITLE
Version Request

### ISSUE THREAD

**Issue by corentinmace** [StickyPiston-development/CreateCobblestone#6]
Hello! Would it be possible to get the version `1.3.1+fabric-1.20.1-36` on CurseForge? I have a modpack on CF that I need to update with this version because of the fix to avoid crashing the servers. I got the problem once and I'd like to avoid getting more of it!

**Comment by MrStickyPiston** [comment]
Uploaded, waiting for approval.

**Comment by MrStickyPiston** [comment]
Approved.

**Comment by corentinmace** [comment]
Thank you very much!
