### ISSUE TITLE
Data or config driven additions

### ISSUE THREAD

**Issue by Grimmspecter** [StickyPiston-development/CreateCobblestone#8]
It would be cool if we could add custom blocks to the generator either via a config(preferred) or via a data pack.
something like EXAMPLE
}
   }
       minecraft:stone
       SU threshold #
       outputamount:
       outputtime:
   
   
   ect ect that way it could be used for modpacks for greater customization then we could configure blocks and make more expensive blocks take a long time and with low output if we want

**Comment by MrStickyPiston** [comment]
In the new beta, included is the option to add generators using a datapack. See for example https://modrinth.com/datapack/create-cobblestone-deepslate-generators.
It only includes the option to add a generator for now but i will be changing this.

**Modrinth**
Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta+fabric-1.20.1-56
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta+forge-1.20.1-56

**Comment by MrStickyPiston** [comment]
I also got the other stuff working: https://www.youtube.com/watch?v=c_1c3vrQKR8

The config for deepslate i used for showcase is:
```json
{
  "block": "minecraft:deepslate",
  "stress": "1024",
  "ratio": "80000"
}
```
When a field is not in the json it will take the value from config.

**Comment by MrStickyPiston** [comment]
I would appreciate it if you could test if this is what you wanted and check for bugs.

**Modrinth**
Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-2+fabric-1.20.1-59
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-2+forge-1.20.1-59

**Comment by MrStickyPiston** [comment]
**Changelog:**
- empty generator is now the first in creative menu
- all generators can now be disabled using datapacks
- /datapack enable/disable now automatically updates generator types, allowing the hotswapping of datapacks
- fixed crash with create liquid fuel
- deepslate generators are now enabled with datapack by default

**Downloads**
Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-3+fabric-1.20.1-65
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-3+forge-1.20.1-65
Example datapack: https://modrinth.com/datapack/create-cobblestone-deepslate-generators/version/1.4.1+1.20.1

**Comment by gniftygnome** [comment]
> I would appreciate it if you could test if this is what you wanted and check for bugs.

I have a mod adding a volcanic rock and cobble from Terrestria via the new data API, and while it works fine on the integrated client/server, when using a discrete server, the client crashes on the first attempt to view the creative inventory.

The top of the stack looks like this (let me know if you need further info, but I'm guessing this is just a matter of the client mod not getting fully initialized).

```
java.lang.NullPointerException: Cannot invoke "net.createcobblestone.data.GeneratorType.getId()" because "net.createcobblestone.data.GeneratorType.NONE" is null
	at net.createcobblestone.index.RegistrateDisplayItemsGenerator.accept(RegistrateDisplayItemsGenerator.java:30) ~[createcobblestone-1.4.1-beta-3+fabric-1.20.1-65.jar:?]
	at net.minecraft.class_1761.method_47306(class_1761.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_7706.method_47338(class_7706.java:2052) ~[client-intermediary.jar:?]
```

**Comment by MrStickyPiston** [comment]
Could you send the datapack and the full log?

**Comment by gniftygnome** [comment]
Log:  https://mclo.gs/qIp7SiF

The datapack is bundled in a mod.  I'll upload that or commit it to github or something, soon.

**Comment by gniftygnome** [comment]
GitHub is a pain sometimes.  Datapack is here:  https://github.com/gniftygnome/cross-pollination/tree/main/src/main/resources/data/createcobblestone/generator_types

**Comment by MrStickyPiston** [comment]
Thank you, im working on it!

**Comment by MrStickyPiston** [comment]
The fabric version is working now, but you need a github account to download it. i will publish it to modrinth once i get it working.

gh actions link: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/11709890769

**Comment by gniftygnome** [comment]
I've confirmed it's fixed.  Thanks!

**Comment by MrStickyPiston** [comment]
On fabric it works, forge will not work and will probably break your existing generators.

**Comment by MrStickyPiston** [comment]
Released on modrinth:
Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-4+fabric-1.20.1-72
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.1-beta-4+forge-1.20.1-72

**Comment by MrStickyPiston** [comment]
Two weeks have past and no unclosed issues were opened, im going to upload the mod to curseforge and modrinth as release soon!

**Comment by MrStickyPiston** [comment]
Released the following on both curseforge and modrinth:
# Create Cobblestone 1.4.1
Warning: wipes all deepslate generators without the deepslate generators datapack

all changes from 1.4.1-beta and above:
- custom generator types using data packs
  - all generator types can be disabled using datapacks
  - generator type datapacks can be hotswapped on both servers and clients using /datapack enable and /datapack disable
  - deepslate generators are now a seperate datapack (https://modrinth.com/datapack/create-cobblestone-deepslate-generators) but are still configurable in the config screen, this way they are more deeply integrated with the mods generator system and this will hopefully lead to less bugs.
  - all generator types can now have a custom stress, ratio and storage amount set using datapacks
  - custom generator types are added to the creative inventory
- reordered generators in creative menu
- updated the mod icon to the new create icon standard
- cleaned up the mods code
- fixed a crash on the client when joining a server

*Modrinth*
Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.1+fabric-1.20.1-73
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.1+forge-1.20.1-73
Deepslate generators datapack: https://modrinth.com/datapack/create-cobblestone-deepslate-generators/version/1.4.1+1.20.1

*Curseforge*
Fabric:  https://www.curseforge.com/minecraft/mc-mods/create-cobblestone/files/5930734
Forge: https://www.curseforge.com/minecraft/mc-mods/create-cobblestone/files/5930737
Deepslate generators datapack: https://legacy.curseforge.com/minecraft/data-packs/create-cobblestone-deepslate-generators/files/5930722

**Comment by MrStickyPiston** [comment]
To everyone who helped with testing: Thank you it helped a lot and a lot of bugs are fixed with your help!
