### ISSUE TITLE
Block Drop

### ISSUE THREAD

**Issue by TheQuickCoder** [StickyPiston-development/CreateCobblestone#9]
When trying to pick up the block, the block breaks quickly but doesnt drop itself.

**Comment by MrStickyPiston** [comment]
Thank you for submitting an issue.
1. What version are you on (mod version+loader)
2. What block? (Generator type)
3. Please send logs

**Comment by GeaRetteX** [comment]
not sure if dead issue, but i'm having the same problem, block breaks instantly (like tnt), and it doesn't drop itself as a block

**Comment by MrStickyPiston** [comment]
> not sure if dead issue, but i'm having the same problem, block breaks instantly (like tnt), and it doesn't drop itself as a block

It is not dead as it is not solved yet. Could you please answer the questions above?

**Comment by MrStickyPiston** [comment]
Closing because nobody gave some info.
